name: Code checks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
      - name: Lint
        run: |
          cd .implement
          uvx --from rust-just just lint
          git diff --exit-code  # In case 'uv run' changed the lockfile.
