name: Integration tests

on:
  pull_request:
    paths:
      - kubernetes-extra/**
      - machine/**
    types:
      - ready_for_review
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  integration-kubernetes-extra:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-kubernetes-extra
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
      - name: Install tox and tox-uv
        run: uv tool install tox --with tox-uv
      - name: Install Concierge
        run: sudo snap install --classic concierge
      - name: Prepare for deploying K8s charms
        run: sudo concierge prepare -p microk8s
      - name: Pack charm
        run: |
          cd kubernetes-extra
          charmcraft pack
      - name: Run integration tests
        run: |
          cd kubernetes-extra
          tox -e integration
      - name: Check handling of .charm files
        run: |
          cd kubernetes-extra
          cp *.charm foo.charm
          CHARM_PATH=foo.charm tox -e integration
          ! CHARM_PATH=bar.charm tox -e integration  # Fails because bar.charm doesn't exist.
          ! tox -e integration  # Fails because there's more than one .charm file.
          rm *.charm
          ! tox -e integration  # Fails because there are no .charm files.

  integration-machine:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-machine
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
      - name: Install tox and tox-uv
        run: uv tool install tox --with tox-uv
      - name: Install Concierge
        run: sudo snap install --classic concierge
      - name: Prepare for deploying machine charms
        run: sudo concierge prepare -p machine
      - name: Pack charm
        run: |
          cd machine
          charmcraft pack
      - name: Run integration tests
        run: |
          cd machine
          tox -e integration
      - name: Check handling of .charm files
        run: |
          cd machine
          cp *.charm foo.charm
          CHARM_PATH=foo.charm tox -e integration
          ! CHARM_PATH=bar.charm tox -e integration  # Fails because bar.charm doesn't exist.
          ! tox -e integration  # Fails because there's more than one .charm file.
          rm *.charm
          ! tox -e integration  # Fails because there are no .charm files.
